---
# The default 'consistent' is a bit confusing and dash/hyphen is easier to have
# in all Markdown files. It also doesn't conflict with asterisk used for bold.
MD004:
  style: dash

# Line length
MD013: false

# Multiple top level headers in the same document
MD025: false

# Trailing punctuation in header
MD026: false

# Inline html
MD033: false

# Bare URL used
MD034: false

# Spaces inside emphasis markers
MD037: false

# First line in a file should be a top-level heading
MD041: false
