
name: auto-update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      - name: update-version
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          
          git config user.name github-actions
          git config user.email github-actions@github.com

          pip install paramiko --upgrade  
          python3 ./Scripts/readme-generator.py

          git add .
          if git commit -m "Syncing with staging repo" | grep -q 'nothing to commit, working tree clean'; then
            echo "Nothing to commit :)"
          else
             git push    
          fi
