name: Teardown

on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - camera1
          - camera2
          - camera3
    env:
      EXREPO: test-acap
      EXNAME: larod-test
      EAPNAME: larod_test
      EXDIR: acap/examples/$EXNAME
    steps:
      - name: remove the application
        run: |
          curl --silent --show-error -u root:"${{secrets.DEVICE_PASSWORD}}" "http://${{secrets.DEVICE_IP}}/${{matrix.arch}}/axis-cgi/applications/control.cgi?action=stop&package=$EAPNAME"
          sleep 5
          curl --silent --show-error -u root:"${{secrets.DEVICE_PASSWORD}}" "http://${{secrets.DEVICE_IP}}/${{matrix.arch}}/axis-cgi/applications/control.cgi?action=remove&package=$EAPNAME"

